# Permalinks
permalink:        pretty

# Setup
title:            The first online knot theory congress
tagline:          'Formal Power Series and Algebraic Combinatorics'
description:      'International conference on knot theory'
url:              #http://fpsac.org
baseurl:          ''

# About/contact
author:
  name:           #'The FPSAC executive committee'
  url:            #http://fpsac.org/
  email:          #executive-office-fpsac@services.cnrs.fr

# paginate:         5
# paginate_path:       "/news/page:num/"
#gems:
#- jekyll-paginate

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/FPSAC/FPSAC.github.io

collections:
  confs:
    output: true

# The current year (fpsac's >= <year> will be mentionned in the upcoming conference list)
year: 2022
